// src-ui/components/live-match-hero.tsx
import { useEffect, useState } from "react"
import type { TFunction } from "i18next"
import { useTranslation } from "react-i18next"
import {
  IconCircleDot,
  IconMap2,
  IconShield,
  IconSwords,
  IconUser,
  IconUsersGroup,
  IconWorld,
} from "@tabler/icons-react"

import { AppIcon } from "@/components/app-icon"
import { agentPortraitUrl, localizedGameNames, mapArt, rankIconUrl, type LocalizedGameNames } from "@/lib/valorant-assets"
import { phaseLabel, playerName, queueLabel } from "@/lib/format"
import { cn } from "@/lib/utils"
import type { LiveSnapshot } from "@/lib/types"

const LIVE_PHASES = new Set(["pregame", "ingame", "range"])

export function LiveMatchHero({ snapshot }: { snapshot: LiveSnapshot | null }) {
  const { t, i18n } = useTranslation()
  const isLive = snapshot ? LIVE_PHASES.has(snapshot.phase) : false
  const agentUrl = agentPortraitUrl(snapshot?.agentId)
  const [mapUrl, setMapUrl] = useState<string | null>(null)
  const [rankUrl, setRankUrl] = useState<string | null>(null)
  const [localizedNames, setLocalizedNames] = useState<LocalizedGameNames | null>(null)

  useEffect(() => {
    let active = true
    setMapUrl(null)
    setRankUrl(null)
    setLocalizedNames(null)
    if (!snapshot) return

    void mapArt(snapshot.mapId, snapshot.mapName).then((art) => {
      if (active) setMapUrl(art?.splash ?? null)
    })
    void rankIconUrl(snapshot.rank?.tier, snapshot.rank?.iconUrl).then((url) => {
      if (active) setRankUrl(url)
    })
    void localizedGameNames(snapshot, i18n.language).then((names) => {
      if (active) setLocalizedNames(names)
    })

    return () => {
      active = false
    }
  }, [snapshot, i18n.language])

  if (!snapshot) {
    return (
      <section className="relative flex flex-1 flex-col overflow-hidden rounded-xl border bg-card">
        <StandbyArt />
        <div className="relative z-10 flex flex-1 flex-col items-center justify-center gap-3 text-center">
          <AppIcon className="size-10 rounded-lg opacity-80" />
          <div>
            <p className="text-base font-semibold">{t("match.waitingTitle")}</p>
            <p className="text-sm text-muted-foreground">{t("match.waitingDescription")}</p>
          </div>
        </div>
        <StatStrip snapshot={null} rankUrl={null} />
      </section>
    )
  }

  const score = snapshot.score
    ? `${snapshot.score.ally} – ${snapshot.score.enemy}`
    : null
  const standby = isLive ? null : standbyCopy(snapshot, t)
  const displayMapName = localizedNames?.mapName ?? snapshot.mapName

  return (
    <section className="relative flex flex-1 flex-col overflow-hidden rounded-xl border bg-card">
      <div className="relative min-h-[16rem] flex-1 overflow-hidden">
        {mapUrl ? (
          <img src={mapUrl} alt="" className="absolute inset-0 size-full object-cover" />
        ) : (
          <StandbyArt />
        )}
        <div className="absolute inset-0 bg-gradient-to-r from-background via-background/40 to-background/10 rtl:bg-gradient-to-l" />
        <div className="absolute inset-0 bg-gradient-to-t from-card via-transparent to-transparent" />

        {agentUrl ? (
          <img
            src={agentUrl}
            alt={localizedNames?.agentName ?? snapshot.agentName ?? ""}
            className="absolute bottom-0 start-0 h-[105%] max-w-[55%] object-contain object-left-bottom drop-shadow-2xl rtl:object-right-bottom"
          />
        ) : null}

        {isLive ? (
          <div className="absolute start-4 top-4 flex items-center gap-2 rounded-md bg-primary px-2.5 py-1 text-xs font-semibold text-primary-foreground shadow-lg">
            <span className="size-1.5 animate-pulse rounded-full bg-current" />
            {t("match.live")}
          </div>
        ) : null}

        {standby ? (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center gap-3 px-6 text-center">
            <AppIcon className="size-10 rounded-lg opacity-80" />
            <div>
              <p className="flex items-center justify-center gap-2 text-base font-semibold">
                <span className="size-1.5 animate-pulse rounded-full bg-success" />
                {standby.title}
              </p>
              <p className="text-sm text-muted-foreground">{standby.subtitle}</p>
            </div>
          </div>
        ) : (
          <div className="absolute end-6 top-1/2 -translate-y-1/2 text-end">
            <AppIcon className="ms-auto size-10 rounded-lg opacity-90" />
            {displayMapName ? (
              <>
                <p className="mt-2 text-xs font-medium tracking-[0.3em] text-muted-foreground">
                  {t("match.mapHeading")}
                </p>
                <p className="text-4xl font-bold tracking-wide text-foreground/90 uppercase">
                  {displayMapName}
                </p>
              </>
            ) : null}
          </div>
        )}
      </div>

      <StatStrip snapshot={snapshot} rankUrl={rankUrl} score={score} localizedNames={localizedNames} />
    </section>
  )
}

function standbyCopy(snapshot: LiveSnapshot, t: TFunction) {
  if (snapshot.phase === "matchmaking") {
    return { title: t("match.findingTitle"), subtitle: t("match.findingDescription") }
  }
  if (snapshot.phase === "menus") {
    return { title: t("match.menusTitle"), subtitle: t("match.menusDescription") }
  }
  return { title: t("match.serviceTitle"), subtitle: t("match.serviceDescription") }
}

function StatStrip({
  snapshot,
  rankUrl,
  score,
  localizedNames,
}: {
  snapshot: LiveSnapshot | null
  rankUrl: string | null
  score?: string | null
  localizedNames?: LocalizedGameNames | null
}) {
  const { t } = useTranslation()
  const empty = t("common.notAvailable")
  const name = playerName(snapshot) ?? empty
  const queue = queueLabel(snapshot?.queueId) ?? empty
  const party = snapshot?.party.size
    ? `${snapshot.party.size} / ${snapshot.party.maxSize ?? snapshot.party.size}`
    : empty
  const agent = localizedNames?.agentName ?? snapshot?.agentName ?? empty
  const map = localizedNames?.mapName ?? snapshot?.mapName ?? empty
  const rankName = localizedNames?.rankName ?? snapshot?.rank?.tierName ??
    (snapshot?.rank?.tier ? t("match.tier", { tier: snapshot.rank.tier }) : t("match.unranked"))
  const rr = snapshot?.rank?.rankedRating != null
    ? `${snapshot.rank.rankedRating} ${t("match.rr")}`
    : empty
  const region = snapshot?.region ? snapshot.region.toUpperCase() : empty

  return (
    <div className="relative z-10 border-t bg-card/95">
      <div className="grid grid-cols-2 gap-x-2 gap-y-2.5 px-4 py-3 sm:grid-cols-3 lg:grid-cols-6">
        <StatCell icon={<IconUser />} label={t("match.player")} value={name} accent />
        <StatCell icon={<IconCircleDot />} label={t("match.queue")} value={queue} />
        <StatCell icon={<IconUsersGroup />} label={t("match.party")} value={party} />
        <StatCell icon={<IconSwords />} label={t("match.score")} value={score ?? empty} />
        <StatCell icon={<IconShield />} label={t("match.agent")} value={agent} />
        <StatCell icon={<IconMap2 />} label={t("match.map")} value={map} />
      </div>
      <div className="grid grid-cols-2 gap-x-2 gap-y-2.5 border-t px-4 py-3 sm:grid-cols-4">
        <StatCell
          icon={<IconCircleDot />}
          label={t("match.phase")}
          value={snapshot ? phaseLabel(snapshot.phase) : empty}
          tone="primary"
        />
        <StatCell
          icon={rankUrl ? <img src={rankUrl} alt="" className="size-5 object-contain" /> : <IconShield />}
          label={t("match.rank")}
          value={rankName}
        />
        <StatCell icon={<IconCircleDot />} label={t("match.rr")} value={rr} />
        <StatCell icon={<IconWorld />} label={t("match.region")} value={region} />
      </div>
    </div>
  )
}

function StatCell({ icon, label, value, accent, tone }: {
  icon: React.ReactNode
  label: string
  value: string
  accent?: boolean
  tone?: "primary"
}) {
  return (
    <div className="flex min-w-0 items-center gap-2.5">
      <span className="flex size-8 shrink-0 items-center justify-center rounded-md bg-muted/60 text-muted-foreground [&_svg]:size-4">
        {icon}
      </span>
      <div className="min-w-0">
        <p className="text-[0.65rem] font-medium tracking-wide text-muted-foreground uppercase">{label}</p>
        <p className={cn("truncate text-sm font-semibold", accent && "text-foreground", tone === "primary" && "text-primary")}>{value}</p>
      </div>
    </div>
  )
}

function StandbyArt() {
  return <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,oklch(0.28_0.06_25/0.6),transparent_55%),radial-gradient(circle_at_80%_80%,oklch(0.25_0.05_264/0.7),transparent_50%)]" />
}

// src-ui/components/live-match-hero.svelte
<script lang="ts">
  import { IconCircleDot, IconMap2, IconShield, IconSwords, IconUser, IconUsersGroup, IconWorld } from "@tabler/icons-svelte"
  import AppIcon from "@/components/app-icon.svelte"
  import StatCell from "@/components/stat-cell.svelte"
  import { phaseLabel, playerName, queueLabel } from "@/lib/format"
  import { locale } from "@/lib/locale.svelte"
  import type { LiveSnapshot, ValorantPresentation } from "@/lib/types"
  let { snapshot, presentation }: { snapshot: LiveSnapshot | null; presentation: ValorantPresentation | null } = $props()
  let isLive = $derived(snapshot ? ["pregame", "ingame", "range"].includes(snapshot.phase) : false)
  let empty = $derived(locale.t("common.notAvailable"))
  let agentUrl = $derived(presentation?.agentPortraitUrl ?? null)
  let mapUrl = $derived(presentation?.mapSplashUrl ?? null)
  let rankUrl = $derived(presentation?.rankIconUrl ?? snapshot?.rank?.iconUrl ?? null)
  let score = $derived(snapshot?.score ? `${snapshot.score.ally} – ${snapshot.score.enemy}` : empty)
  let standby = $derived(snapshot && !isLive ? snapshot.phase === "matchmaking" ? { title: locale.t("match.findingTitle"), subtitle: locale.t("match.findingDescription") } : snapshot.phase === "menus" ? { title: locale.t("match.menusTitle"), subtitle: locale.t("match.menusDescription") } : { title: locale.t("match.serviceTitle"), subtitle: locale.t("match.serviceDescription") } : null)
  let name = $derived(playerName(snapshot) ?? empty)
  let queue = $derived(queueLabel(snapshot?.queueId, snapshot?.queueKey) ?? empty)
  let party = $derived(snapshot?.party.size ? `${snapshot.party.size} / ${snapshot.party.maxSize ?? snapshot.party.size}` : empty)
  let agent = $derived(presentation?.agentName ?? snapshot?.agentName ?? empty)
  let map = $derived(presentation?.mapName ?? snapshot?.mapName ?? empty)
  let rank = $derived(presentation?.rankName ?? snapshot?.rank?.tierName ?? (snapshot?.rank?.tier ? locale.t("match.tier", { tier: snapshot.rank.tier }) : locale.t("match.unranked")))
  let rr = $derived(snapshot?.rank?.rankedRating != null ? `${snapshot.rank.rankedRating} ${locale.t("match.rr")}` : empty)
  let region = $derived(snapshot?.region ? snapshot.region.toUpperCase() : empty)
</script>
<section class="relative flex flex-1 flex-col overflow-hidden rounded-xl border bg-card">
  {#if !snapshot}<div class="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,oklch(0.28_0.06_25/0.6),transparent_55%),radial-gradient(circle_at_80%_80%,oklch(0.25_0.05_264/0.7),transparent_50%)]"></div><div class="relative z-10 flex flex-1 flex-col items-center justify-center gap-3 text-center"><AppIcon class="size-10 rounded-lg opacity-80" /><div><p class="text-base font-semibold">{locale.t("match.waitingTitle")}</p><p class="text-sm text-muted-foreground">{locale.t("match.waitingDescription")}</p></div></div>
  {:else}<div class="relative min-h-[16rem] flex-1 overflow-hidden">{#if mapUrl}<img src={mapUrl} alt="" class="absolute inset-0 size-full object-cover" />{:else}<div class="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,oklch(0.28_0.06_25/0.6),transparent_55%),radial-gradient(circle_at_80%_80%,oklch(0.25_0.05_264/0.7),transparent_50%)]"></div>{/if}<div class="absolute inset-0 bg-gradient-to-r from-background via-background/40 to-background/10 rtl:bg-gradient-to-l"></div><div class="absolute inset-0 bg-gradient-to-t from-card via-transparent to-transparent"></div>{#if agentUrl}<img src={agentUrl} alt={agent} class="absolute bottom-0 start-0 h-[105%] max-w-[55%] object-contain object-left-bottom drop-shadow-2xl rtl:object-right-bottom" />{/if}{#if isLive}<div class="absolute start-4 top-4 flex items-center gap-2 rounded-md bg-primary px-2.5 py-1 text-xs font-semibold text-primary-foreground shadow-lg"><span class="size-1.5 animate-pulse rounded-full bg-current"></span>{locale.t("match.live")}</div>{/if}{#if standby}<div class="absolute inset-0 z-10 flex flex-col items-center justify-center gap-3 px-6 text-center"><AppIcon class="size-10 rounded-lg opacity-80" /><div><p class="flex items-center justify-center gap-2 text-base font-semibold"><span class="size-1.5 animate-pulse rounded-full bg-success"></span>{standby.title}</p><p class="text-sm text-muted-foreground">{standby.subtitle}</p></div></div>{:else}<div class="absolute end-6 top-1/2 -translate-y-1/2 text-end"><AppIcon class="ms-auto size-10 rounded-lg opacity-90" />{#if map !== empty}<p class="mt-2 text-xs font-medium tracking-[0.3em] text-muted-foreground">{locale.t("match.mapHeading")}</p><p class="text-4xl font-bold tracking-wide text-foreground/90 uppercase">{map}</p>{/if}</div>{/if}</div>{/if}
  <div class="relative z-10 border-t bg-card/95"><div class="grid grid-cols-2 gap-x-2 gap-y-2.5 px-4 py-3 sm:grid-cols-3 lg:grid-cols-6">
    <StatCell label={locale.t("match.player")} value={name} accent>{#snippet icon()}<IconUser />{/snippet}</StatCell><StatCell label={locale.t("match.queue")} value={queue}>{#snippet icon()}<IconCircleDot />{/snippet}</StatCell><StatCell label={locale.t("match.party")} value={party}>{#snippet icon()}<IconUsersGroup />{/snippet}</StatCell><StatCell label={locale.t("match.score")} value={score}>{#snippet icon()}<IconSwords />{/snippet}</StatCell><StatCell label={locale.t("match.agent")} value={agent}>{#snippet icon()}<IconShield />{/snippet}</StatCell><StatCell label={locale.t("match.map")} value={map}>{#snippet icon()}<IconMap2 />{/snippet}</StatCell>
  </div><div class="grid grid-cols-2 gap-x-2 gap-y-2.5 border-t px-4 py-3 sm:grid-cols-4"><StatCell label={locale.t("match.phase")} value={snapshot ? phaseLabel(snapshot.phase) : empty} tone>{#snippet icon()}<IconCircleDot />{/snippet}</StatCell><StatCell label={locale.t("match.rank")} value={rank}>{#snippet icon()}{#if rankUrl}<img src={rankUrl} alt="" class="size-5 object-contain" />{:else}<IconShield />{/if}{/snippet}</StatCell><StatCell label={locale.t("match.rr")} value={rr}>{#snippet icon()}<IconCircleDot />{/snippet}</StatCell><StatCell label={locale.t("match.region")} value={region}>{#snippet icon()}<IconWorld />{/snippet}</StatCell></div></div>
</section>
