// src-ui/components/quick-info-card.tsx
import {
  IconBrandDiscord,
  IconBroadcast,
  IconClockHour4,
  IconInfoCircle,
  IconTargetArrow,
} from "@tabler/icons-react"
import { useTranslation } from "react-i18next"

import { Panel } from "@/components/panel"
import { formatTime } from "@/lib/format"
import { cn } from "@/lib/utils"
import type { LiveSnapshot, OverlayStatus, RpcStatus } from "@/lib/types"

const LIVE_PHASES = new Set(["pregame", "ingame", "range"])

export function QuickInfoCard({
  overlay,
  rpc,
  snapshot,
  lastSync,
}: {
  overlay: OverlayStatus
  rpc: RpcStatus
  snapshot: LiveSnapshot | null
  lastSync: Date | null
}) {
  const { t } = useTranslation()
  const tracking = snapshot ? LIVE_PHASES.has(snapshot.phase) : false

  const rows = [
    {
      icon: <IconBroadcast />,
      label: t("quickInfo.overlay"),
      value: overlay.enabled ? t("common.ready") : t("common.off"),
      good: overlay.enabled,
    },
    {
      icon: <IconBrandDiscord />,
      label: t("quickInfo.discord"),
      value: rpc.connected ? t("common.ready") : rpc.enabled ? t("common.connecting") : t("common.off"),
      good: rpc.connected,
    },
    {
      icon: <IconTargetArrow />,
      label: t("quickInfo.tracking"),
      value: tracking ? t("common.active") : t("common.idle"),
      good: tracking,
    },
    {
      icon: <IconClockHour4 />,
      label: t("quickInfo.lastSync"),
      value: formatTime(lastSync),
      good: undefined,
    },
  ]

  return (
    <Panel icon={<IconInfoCircle />} title={t("quickInfo.title")}>
      <div className="flex flex-col">
        {rows.map((row) => (
          <div
            key={row.label}
            className="flex items-center justify-between gap-3 border-t border-border/60 py-2 first:border-t-0"
          >
            <span className="flex items-center gap-2.5 text-sm text-muted-foreground [&_svg]:size-4">
              {row.icon}
              <span className="text-foreground">{row.label}</span>
            </span>
            <span
              className={cn(
                "text-sm font-semibold",
                row.good === true && "text-success",
                row.good === false && "text-muted-foreground",
                row.good === undefined && "font-mono text-foreground",
              )}
            >
              {row.value}
            </span>
          </div>
        ))}
      </div>
    </Panel>
  )
}

// src-ui/components/quick-info-card.svelte
<script lang="ts">
  import { IconBrandDiscord, IconBroadcast, IconClockHour4, IconInfoCircle, IconTargetArrow } from "@tabler/icons-svelte"
  import Panel from "@/components/panel.svelte"
  import RelativeTime from "@/components/relative-time.svelte"
  import { locale } from "@/lib/locale.svelte"
  import type { LiveSnapshot, OverlayStatus, RpcStatus } from "@/lib/types"
  let { overlay, rpc, snapshot, lastSync, now }: { overlay: OverlayStatus; rpc: RpcStatus; snapshot: LiveSnapshot | null; lastSync: Date | null; now: number } = $props()
  let tracking = $derived(snapshot ? ["pregame", "ingame", "range"].includes(snapshot.phase) : false)
</script>
<Panel title={locale.t("quickInfo.title")}>{#snippet icon()}<IconInfoCircle />{/snippet}<div class="flex flex-col">
  <div class="row"><span><IconBroadcast />{locale.t("quickInfo.overlay")}</span><strong class:text-success={overlay.enabled}>{overlay.enabled ? locale.t("common.ready") : locale.t("common.off")}</strong></div>
  <div class="row"><span><IconBrandDiscord />{locale.t("quickInfo.discord")}</span><strong class:text-success={rpc.connected}>{rpc.connected ? locale.t("common.ready") : rpc.enabled ? locale.t("common.connecting") : locale.t("common.off")}</strong></div>
  <div class="row"><span><IconTargetArrow />{locale.t("quickInfo.tracking")}</span><strong class:text-success={tracking}>{tracking ? locale.t("common.active") : locale.t("common.idle")}</strong></div>
  <div class="row"><span><IconClockHour4 />{locale.t("quickInfo.lastSync")}</span><strong class="font-mono text-foreground"><RelativeTime date={lastSync} {now} fallback="--:--" /></strong></div>
</div></Panel>
<style>.row{display:flex;width:100%;align-items:center;justify-content:space-between;gap:.75rem;border-top:1px solid color-mix(in oklab,var(--border) 60%,transparent);padding:.5rem 0;line-height:1.25rem}.row:first-child{border-top:0}.row span{display:flex;align-items:center;gap:.625rem;font-size:.875rem;color:var(--foreground)}.row span :global(svg){width:1rem;height:1rem;color:var(--muted-foreground)}.row strong{font-size:.875rem;font-weight:600;color:var(--muted-foreground)}</style>
