// src-ui/components/status-bar.svelte
<script lang="ts">
  import { IconClockHour4, IconRefreshDot, IconWifi } from "@tabler/icons-svelte"
  import RelativeTime from "@/components/relative-time.svelte"
  import { locale } from "@/lib/locale.svelte"
  import { formatUptime } from "@/lib/format"
  import { cn } from "@/lib/utils"
  import type { CoreStatus } from "@/lib/types"
  let { status, lastSync, startedAt, now }: { status: CoreStatus; lastSync: Date | null; startedAt: number; now: number } = $props()
  let health = $derived(status.kind === "valorantReady" ? { label: locale.t("statusBar.excellent"), tone: "text-success" } : status.kind === "riotClientOnly" || status.kind === "valorantLaunching" || status.kind === "degraded" ? { label: locale.t(status.kind === "degraded" ? "statusBar.degraded" : "statusBar.good"), tone: "text-chart-4" } : status.kind === "error" || status.kind === "noRiotInstall" || status.kind === "authExpired" ? { label: locale.t("statusBar.error"), tone: "text-destructive" } : { label: locale.t("statusBar.offline"), tone: "text-muted-foreground" })
</script>
<footer class="flex h-11 shrink-0 items-center border-t bg-background/80 px-4 text-xs backdrop-blur">
  <div class="flex items-center gap-4 text-muted-foreground"><span class="flex items-center gap-1.5"><IconWifi class={cn("size-4", health.tone)} />{locale.t("statusBar.connectionHealth")} <strong class={cn("font-semibold", health.tone)}>{health.label}</strong></span><span class="h-4 w-px bg-border"></span><span class="flex items-center gap-1.5"><IconRefreshDot class="size-4" />{locale.t("statusBar.lastSync")} <strong class="font-mono font-normal text-foreground"><RelativeTime date={lastSync} {now} fallback="--:--" /></strong></span><span class="h-4 w-px bg-border"></span><span class="flex items-center gap-1.5"><IconClockHour4 class="size-4" />{locale.t("statusBar.uptime")} <strong class="font-mono font-normal text-foreground">{formatUptime(now - startedAt)}</strong></span></div>
</footer>

// src-ui/components/status-bar.tsx
import {
  IconClockHour4,
  IconFileText,
  IconRefreshDot,
  IconWifi,
} from "@tabler/icons-react"
import { toast } from "sonner"
import { useTranslation } from "react-i18next"

import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { formatTime, formatUptime } from "@/lib/format"
import { cn } from "@/lib/utils"
import type { CoreStatus } from "@/lib/types"

function connectionHealth(status: CoreStatus): {
  key: string
  tone: string
} {
  switch (status.kind) {
    case "valorantReady":
      return { key: "statusBar.excellent", tone: "text-success" }
    case "riotClientOnly":
    case "valorantLaunching":
      return { key: "statusBar.good", tone: "text-chart-4" }
    case "degraded":
      return { key: "statusBar.degraded", tone: "text-chart-4" }
    case "error":
    case "authExpired":
    case "noRiotInstall":
      return { key: "statusBar.error", tone: "text-destructive" }
    default:
      return { key: "statusBar.offline", tone: "text-muted-foreground" }
  }
}

export function StatusBar({
  status,
  lastSync,
  uptimeMs,
}: {
  status: CoreStatus
  lastSync: Date | null
  uptimeMs: number
}) {
  const { t } = useTranslation()
  const health = connectionHealth(status)

  return (
    <footer className="flex h-11 shrink-0 items-center justify-between gap-4 border-t bg-background/80 px-4 text-xs backdrop-blur">
      <div className="flex items-center gap-4 text-muted-foreground">
        <span className="flex items-center gap-1.5">
          <IconWifi className={cn("size-4", health.tone)} />
          {t("statusBar.connectionHealth")}
          <span className={cn("font-semibold", health.tone)}>
            {t(health.key)}
          </span>
        </span>
        <Separator orientation="vertical" className="h-4" />
        <span className="flex items-center gap-1.5">
          <IconRefreshDot className="size-4" />
          {t("statusBar.lastSync")}
          <span className="font-mono text-foreground">
            {formatTime(lastSync)}
          </span>
        </span>
        <Separator orientation="vertical" className="h-4" />
        <span className="flex items-center gap-1.5">
          <IconClockHour4 className="size-4" />
          {t("statusBar.uptime")}
          <span className="font-mono text-foreground">
            {formatUptime(uptimeMs)}
          </span>
        </span>
      </div>

      <div className="flex items-center gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={() => toast.info(t("statusBar.logsSoon"))}
        >
          <IconFileText data-icon="inline-start" />
          {t("statusBar.logs")}
        </Button>
      </div>
    </footer>
  )
}
