// src-ui/components/updates-card.tsx
import { useTranslation } from "react-i18next"
import {
  IconCalendarEvent,
  IconClockCheck,
  IconDownload,
  IconRefresh,
  IconRocket,
  IconShieldCheck,
  IconSparkles,
  IconTag,
} from "@tabler/icons-react"

import { Button } from "@/components/ui/button"
import { Panel } from "@/components/panel"
import { formatDate, formatTime } from "@/lib/format"
import { translateMessage } from "@/lib/localized-message"
import { cn } from "@/lib/utils"
import type { UpdaterState } from "@/lib/types"

export function UpdatesCard({ updater, version, canInstall, lastChecked, onCheck, onInstall }: {
  updater: UpdaterState
  version: string | null
  canInstall: boolean
  lastChecked: Date | null
  onCheck: () => void
  onInstall: () => void
}) {
  const { t } = useTranslation()
  const checking = updater.status === "checking" || updater.status === "installing"
  const current = updater.currentVersion ?? version ?? t("common.notAvailable")
  const hasUpdate = updater.status === "available" && Boolean(updater.version)
  const releaseNotes = hasUpdate ? cleanNotes(updater.body) : null

  return (
    <Panel icon={<IconRocket />} title={t("updates.title")}>
      <div className="flex flex-col gap-2.5">
        <div className="flex flex-col">
          <InfoRow icon={<IconTag />} label={t("updates.currentVersion")} value={`v${current}`} mono />
          <InfoRow icon={<IconRocket />} label={t("updates.status")} value={statusLabel(updater, t)} valueClassName={statusTone(updater.status)} />
          <InfoRow icon={<IconClockCheck />} label={t("updates.lastChecked")} value={lastChecked ? formatTime(lastChecked) : t("updates.never")} mono />
          {hasUpdate ? <InfoRow icon={<IconSparkles />} label={t("updates.latestVersion")} value={`v${updater.version}`} valueClassName="text-primary" mono /> : null}
          {hasUpdate && updater.date ? <InfoRow icon={<IconCalendarEvent />} label={t("updates.released")} value={formatDate(new Date(updater.date.replace(/ \d{2}:\d{2}:\d{2}.*$/, "")))} mono /> : null}
        </div>
        {updater.status === "installing" ? (
          <div className="flex flex-col gap-1.5">
            <div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-[width]" style={{ width: `${updater.progress ?? 35}%` }} /></div>
            <p className="text-xs text-muted-foreground">{translateMessage(t, updater.message)}</p>
          </div>
        ) : <p className={cn("text-xs", updater.status === "error" ? "text-destructive" : "text-muted-foreground")}>{translateMessage(t, updater.message)}</p>}
        {releaseNotes ? <div className="rounded-lg border bg-background/40 p-3"><p className="mb-1 flex items-center gap-1.5 text-xs font-semibold text-foreground"><IconSparkles className="size-3.5 text-primary" />{t("updates.whatsNew")}</p><p className="line-clamp-3 text-xs whitespace-pre-line text-muted-foreground">{releaseNotes}</p></div> : null}
        <p className="flex items-center gap-1.5 text-xs text-muted-foreground"><IconShieldCheck className="size-3.5 text-success" />{t("updates.signed")}</p>
        <div className="grid grid-cols-2 gap-2">
          <Button variant="outline" size="sm" onClick={onCheck} disabled={checking}><IconRefresh data-icon="inline-start" />{t("updates.check")}</Button>
          <Button size="sm" onClick={onInstall} disabled={!canInstall || checking}><IconDownload data-icon="inline-start" />{t("updates.install")}</Button>
        </div>
      </div>
    </Panel>
  )
}

function InfoRow({ icon, label, value, mono, valueClassName }: { icon: React.ReactNode; label: string; value: string; mono?: boolean; valueClassName?: string }) {
  return <div className="flex items-center justify-between gap-3 border-t border-border/60 py-1.5 first:border-t-0"><span className="flex items-center gap-2.5 text-sm text-muted-foreground [&_svg]:size-4">{icon}<span className="text-foreground">{label}</span></span><span className={cn("text-sm font-semibold", mono && "font-mono", valueClassName)}>{value}</span></div>
}

function cleanNotes(body?: string | null) {
  const trimmed = body?.trim()
  return trimmed && trimmed.length > 0 ? trimmed : null
}

function statusLabel(updater: UpdaterState, t: ReturnType<typeof useTranslation>["t"]) {
  if (updater.status === "available") return t("updates.availableShort", { version: updater.version })
  return t(`updates.state.${updater.status}`)
}

function statusTone(status: UpdaterState["status"]) {
  if (status === "current" || status === "installed") return "text-success"
  if (status === "available") return "text-primary"
  if (status === "error") return "text-destructive"
  return "text-muted-foreground"
}

// src-ui/components/updates-card.svelte
<script lang="ts">
  import { IconCalendarEvent, IconClockCheck, IconDownload, IconRefresh, IconRocket, IconShieldCheck, IconSparkles, IconTag } from "@tabler/icons-svelte"
  import Panel from "@/components/panel.svelte"
  import RelativeTime from "@/components/relative-time.svelte"
  import { Button } from "@/components/ui/button"
  import { formatDate } from "@/lib/format"
  import { locale } from "@/lib/locale.svelte"
  import { cn } from "@/lib/utils"
  import type { UpdaterState } from "@/lib/types"
  let { updater, version, canInstall, lastChecked, now, onCheck, onInstall }: { updater: UpdaterState; version: string | null; canInstall: boolean; lastChecked: Date | null; now: number; onCheck: () => void; onInstall: () => void } = $props()
  let selected = $state<"current" | "latest" | null>(null)
  let DialogComponent = $state<any>(null)
  let checking = $derived(updater.status === "checking" || updater.status === "installing")
  let current = $derived(updater.currentVersion ?? version ?? locale.t("common.notAvailable"))
  let hasUpdate = $derived(updater.status === "available" && Boolean(updater.version))
  let releaseNotes = $derived(hasUpdate ? updater.body?.trim() || null : null)
  let status = $derived(updater.status === "available" ? locale.t("updates.availableShort", { version: updater.version }) : locale.t(`updates.state.${updater.status}`))
  let message = $derived(updater.message.detail ? locale.t("errors.withDetail", { message: locale.t(updater.message.key, updater.message.args), detail: updater.message.detail }) : locale.t(updater.message.key, updater.message.args))
  async function openRelease(kind: "current" | "latest") { selected = kind; DialogComponent = (await import("@/components/release-notes-dialog.svelte")).default }
</script>
<Panel title={locale.t("updates.title")}>{#snippet icon()}<IconRocket />{/snippet}<div class="flex flex-col gap-2.5"><div class="flex flex-col">
  <button type="button" class="info-row rounded-sm text-start transition-colors hover:bg-muted/50 focus-visible:ring-2 focus-visible:ring-ring" onclick={() => openRelease("current")} disabled={current === locale.t("common.notAvailable")}><span><IconTag />{locale.t("updates.currentVersion")}</span><strong class="font-mono">v{current}</strong></button>
  <div class="info-row"><span><IconRocket />{locale.t("updates.status")}</span><strong class={updater.status === "available" ? "text-primary" : updater.status === "error" ? "text-destructive" : updater.status === "current" ? "text-success" : "text-muted-foreground"}>{status}</strong></div>
  <div class="info-row"><span><IconClockCheck />{locale.t("updates.lastChecked")}</span><strong class="font-mono"><RelativeTime date={lastChecked} {now} fallback={locale.t("updates.never")} coarse /></strong></div>
  {#if hasUpdate}<button type="button" class="info-row rounded-sm text-start transition-colors hover:bg-muted/50 focus-visible:ring-2 focus-visible:ring-ring" aria-label={`${locale.t("updates.latestVersion")} v${updater.version}`} onclick={() => openRelease("latest")}><span><IconSparkles />{locale.t("updates.latestVersion")}</span><strong class="font-mono text-primary">v{updater.version}</strong></button>{/if}
  {#if hasUpdate && updater.date}<div class="info-row"><span><IconCalendarEvent />{locale.t("updates.released")}</span><strong class="font-mono">{formatDate(new Date(updater.date.replace(/ \d{2}:\d{2}:\d{2}.*$/, "")))}</strong></div>{/if}
  </div>{#if updater.status === "installing"}<div class="flex flex-col gap-1.5"><div class="h-1.5 overflow-hidden rounded-full bg-muted"><div class="h-full rounded-full bg-primary transition-[width]" style:width={`${updater.progress ?? 35}%`}></div></div><p class="text-xs text-muted-foreground">{message}</p></div>{:else}<p class={cn("text-xs", updater.status === "error" ? "text-destructive" : "text-muted-foreground")}>{message}</p>{/if}
  {#if releaseNotes}<div class="rounded-lg border bg-background/40 p-3"><p class="mb-1 flex items-center gap-1.5 text-xs font-semibold text-foreground"><IconSparkles class="size-3.5 text-primary" />{locale.t("updates.whatsNew")}</p><p class="line-clamp-3 text-xs whitespace-pre-line text-muted-foreground">{releaseNotes}</p></div>{/if}<p class="flex items-center gap-1.5 text-xs text-muted-foreground"><IconShieldCheck class="size-3.5 text-success" />{locale.t("updates.signed")}</p><div class="grid grid-cols-2 gap-2"><Button variant="outline" size="sm" onclick={onCheck} disabled={checking} aria-busy={updater.status === "checking"}><IconRefresh data-icon="inline-start" class={updater.status === "checking" ? "animate-spin" : undefined} />{locale.t("updates.check")}</Button><Button size="sm" onclick={onInstall} disabled={!canInstall || checking}><IconDownload data-icon="inline-start" />{locale.t("updates.install")}</Button></div></div></Panel>
{#if selected && DialogComponent}<DialogComponent open={true} onOpenChange={(open: boolean) => { if (!open) selected = null }} fetchFromGitHub={selected === "current"} release={selected === "latest" ? { version: updater.version ?? "", body: updater.body, date: updater.date } : { version: current }} />{/if}
<style>.info-row{display:flex;width:100%;align-items:center;justify-content:space-between;gap:.75rem;border-top:1px solid color-mix(in oklab,var(--border) 60%,transparent);padding:.375rem 0;line-height:1.25rem}.info-row:first-child{border-top:0}.info-row span{display:flex;align-items:center;gap:.625rem;font-size:.875rem;color:var(--foreground)}.info-row span :global(svg){width:1rem;height:1rem;color:var(--muted-foreground)}.info-row strong{font-size:.875rem;font-weight:600}</style>
